### ISSUE TITLE
Nakon logina ... promjeniti tekst u zaglavlju Bok <Ime> u Hej <Ime>

### ISSUE THREAD

**Issue by renta75** [grozdanowski/booking-for-relief-frontend#5]
![image](https://user-images.githubusercontent.com/12384828/103946730-4bb2eb00-5137-11eb-8353-6d80e743efd6.png)

**Comment by grozdanowski** [comment]
Hahaha - zašto? :D

**Comment by grozdanowski** [comment]
Ovo definitivno nije sad prioritet - kad dođe do generalnog wordinga web-a, zabavljati ćemo se time.
