### ISSUE TITLE
1. prioritet - Dodati Floating button ("Dodaj") u mobilnoj rezoluciji+ okrenuti poredak pod hamburgerom

### ISSUE THREAD

**Issue by renta75** [grozdanowski/booking-for-relief-frontend#8]
Najhitnija funkcija je "zavučena" pod Hamburger->PREGLEDI I SEARCH>Pa tek onda ...
Dodatno okrenuti poredak Hamburger->Unos->PREGLEDI I SEARCH.

**Comment by grozdanowski** [comment]
Done.
